//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multichain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multichain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        internal static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {error: &quot;Account valided&quot;}.
        /// </summary>
        internal static string AccountValidError {
            get {
                return ResourceManager.GetString("AccountValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string grant_type_password {
            get {
                return ResourceManager.GetString("grant_type_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant permission fail.
        /// </summary>
        internal static string GrantFail {
            get {
                return ResourceManager.GetString("GrantFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant permission sucess.
        /// </summary>
        internal static string GrantSucess {
            get {
                return ResourceManager.GetString("GrantSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Susscess issue asset.
        /// </summary>
        internal static string IssueSucess {
            get {
                return ResourceManager.GetString("IssueSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error send OTP to mail.
        /// </summary>
        internal static string SendMailError {
            get {
                return ResourceManager.GetString("SendMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent from your email.
        /// </summary>
        internal static string SentEmailMessage {
            get {
                return ResourceManager.GetString("SentEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { error : &quot;UnAuthoiation&quot;}.
        /// </summary>
        internal static string UnAuthError {
            get {
                return ResourceManager.GetString("UnAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not yours.
        /// </summary>
        internal static string UnValidAddress {
            get {
                return ResourceManager.GetString("UnValidAddress", resourceCulture);
            }
        }
    }
}
